# This is a config for E2B sandbox template.
# You can use template ID (4d4kz1te1dtbkcqkm5x4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("4d4kz1te1dtbkcqkm5x4") # Sync sandbox
# sandbox = await AsyncSandbox.create("4d4kz1te1dtbkcqkm5x4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('4d4kz1te1dtbkcqkm5x4')

team_id = "dc32c6cf-74f3-4344-b1d9-ca680dbcf7e4"
start_cmd = "cd react-app && npm run dev"
dockerfile = "e2b.Dockerfile"
template_id = "4d4kz1te1dtbkcqkm5x4"
